---
- name: Install Docker daemon on host
  hosts: docker
  become: true
  vars:
  tasks:
    - name: Install required system packages
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - python3-pip
      tags: install

    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present
      tags: install

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu bionic stable
        state: present
      tags: install

    - name: Update apt and install docker-ce
      apt: name={{ item }} state=latest update_cache=yes
      with_items:
        - docker-ce
        - docker-ce-cli
        - containerd.io
      tags: install

    - name: Install Docker Module for Python
      pip:
        name: docker
      tags: install
