---
- name: Install Docker daemon on host
  hosts: docker
  become: true
  vars:
  tasks:
    - name: Pull reddit docker image
      docker_image:
        name: azatrg/otus-reddit
        source: pull
      tags: docker-pull

    - name: Create reddit container
      docker_container:
        name: reddit
        image: "azatrg/otus-reddit"
        network_mode: host
        state: started
      tags: docker-run
