name: Run Terraform configs validation

on: [push, pull_request]

jobs:
  terraform:
    runs-on: ubuntu-latest
    # strategy:
    #   matrix:
    #     environment: ["stage", "prod"]
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 0.12.8
    - name: Terraform Init
      id: init
      run: terraform init --backend=false
      working-directory: ./docker-monolith/infra/terraform

    - name: Terraform Validate
      id: validate
      run: terraform validate
      working-directory: ./docker-monolith/infra/terraform

    - uses: terraform-linters/setup-tflint@v1
      name: Setup TFLint

    - name: Init TFLint
      run: tflint --init  ./docker-monolith/infra/terraform

    - name: Run TFLint
      run: tflint -f checkstyle  --loglevel=info ./docker-monolith/infra/terraform
